[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lermodel"
version = "0.1.0"
description = "Pydantic data model for LER (LedningsEjerRegister) features"
authors = [
    { name = "Thomas Wessel", email = "mrvelle@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2",
    "shapely>=2",
    "lxml>=5",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "nox",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["I"]
