"""
Autogenerated table of which LER feature types this package implements per
version - see clay/adr/944 (in the sibling clay repo):

    "Der skal også være en autogeneret tabel i lermodels docs, der viser
    hvad der er supported i de forskellige versioner."

README.md embeds this table between the SUPPORT_TABLE_START/END markers;
`python scripts/update_readme.py` regenerates it, and a test asserts the
README copy is up to date.
"""

from lermodel import v2_1_0

# Add future version modules here as they're implemented.
VERSIONS = {
    v2_1_0.SCHEMA_VERSION: v2_1_0,
}


def generate_support_table() -> str:
    """Markdown table of feature types x LER versions, ✅ where implemented."""
    versions = list(VERSIONS)
    all_feature_types: dict[str, None] = {}
    for module in VERSIONS.values():
        for feature_type in module.ALL_FEATURE_TYPES:
            all_feature_types[feature_type] = None

    header = "| Feature type | " + " | ".join(versions) + " |"
    separator = "| --- | " + " | ".join("---" for _ in versions) + " |"
    rows = [header, separator]
    for feature_type in sorted(all_feature_types):
        cells = []
        for version in versions:
            module = VERSIONS[version]
            implemented = (
                feature_type in module.ALL_FEATURE_TYPES and feature_type in module.FEATURE_TYPE_MAP
            )
            cells.append("✅" if implemented else "")
        rows.append(f"| {feature_type} | " + " | ".join(cells) + " |")

    return "\n".join(rows) + "\n"
