"""
Autogenerated table of which LER feature types this package implements per
version - see clay/adr/944.

Called by maintainance script `update_version_support.py`.
"""

from lermodel.registry import VERSIONS


def generate_support_table() -> str:
    """Markdown table of feature types x LER versions, ✅ where implemented."""
    versions = list(VERSIONS)
    all_feature_types: dict[str, None] = {}
    for module in VERSIONS.values():
        for feature_type in module.ALL_FEATURE_TYPES:
            all_feature_types[feature_type] = None

    header = "| Feature type | " + " | ".join(versions) + " |"
    separator = "| --- | " + " | ".join("---" for _ in versions) + " |"
    rows = [header, separator]
    for feature_type in sorted(all_feature_types):
        cells = []
        for version in versions:
            module = VERSIONS[version]
            implemented = (
                feature_type in module.ALL_FEATURE_TYPES and feature_type in module.FEATURE_TYPE_MAP
            )
            cells.append("✅" if implemented else "")
        rows.append(f"| {feature_type} | " + " | ".join(cells) + " |")

    return "\n".join(rows) + "\n"
