"""Regenerate VERSION_SUPPORT.md, the supported-feature-types table."""

from pathlib import Path

from lermodel.support import generate_support_table

HEADER = (
    "# Supported LER feature types\n"
    "\n"
    "Autogenerated by `python scripts/update_version_support.py` - do not edit by hand.\n"
    "\n"
)


def main() -> None:
    version_support_path = Path(__file__).resolve().parent.parent / "VERSION_SUPPORT.md"
    version_support_path.write_text(HEADER + generate_support_table())


if __name__ == "__main__":
    main()
